application: abransbywilliams
version: 1
runtime: python27
api_version: 1
threadsafe: true
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^client/app/.*$
- ^client/node_modules/.*$
- ^client/test/.*$
- ^client/tools/.*$
- ^server/tests/.*$
- ^server/testrunner.py$
- ^env/.*$
- ^(.*/)\.\w+$
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: client/deploy/css
  secure: always

- url: /js
  static_dir: client/deploy/js
  secure: always

- url: /img
  static_dir: client/deploy/img
  secure: always

- url: /
  script: server.start.app

- url: /technical-skills
  script: server.start.app

- url: /cv
  script: server.start.app

- url: /cv/(.*?)/full
  script: server.start.app
  login: admin

- url: /cv/.*
  script: server.start.app

- url: /skills
  script: server.api.app

- url: /skills/.*
  script: server.api.app

- url: /development-methods
  script: server.start.app

- url: /leadership
  script: server.start.app

- url: /attributes
  script: server.start.app

- url: /employment
  script: server.start.app

- url: /contact
  script: server.start.app
  secure: always

- url: /contact/sent
  script: server.start.app
  secure: always

- url: /copyright
  script: server.start.app

- url: /privacy-policy
  script: server.start.app

- url: /cookie-policy
  script: server.start.app

- url: /import/.*
  script: server.api.app
  login: admin

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

inbound_services:
- mail
- warmup
